#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_USE_QRCODE 1
#define LV_USE_CANVAS 1
#define LV_MEM_SIZE (64 * 1024U)
#define LV_USE_OS LV_OS_NONE
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_USE_LOG 0
#endif
