#!/usr/bin/env python3
"""Generate deterministic UI catalog and Latin/CJK subsets (Pillow 11.3.0).

Input: Noto Sans CJK JP Regular from noto-cjk Sans2.004, commit
523d033d6cb47f4a80c58a35753646f5c3608a78, SIL OFL 1.1.
Pass its OTF path; generated C is checked in, so normal builds are offline.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]


def catalog():
    rows = []
    seen = set()
    for line in (ROOT / "components/vibe_ui/messages.tsv").read_text().splitlines():
        row = [s.replace(r"\n", "\n") for s in line.split("|")]
        assert len(row) == 4 and all(row), line
        assert row[0].lower() not in seen, row[0]
        seen.add(row[0].lower())
        rows.append(row)
    return rows


def bitmap(font, cp, width, height, baseline):
    # One alphabetic origin for EVERY glyph: never center by ink bounds.
    # A padded render also proves no ascender/descender was silently cropped.
    pad = 8
    padded = Image.new("L", (width + 2 * pad, height + 2 * pad))
    # A shared 1px left bearing preserves negative-bearing Latin glyphs (j).
    ImageDraw.Draw(padded).text((pad + 1, pad + baseline), chr(cp), font=font,
                               anchor="ls", fill=255)
    image = padded.crop((pad, pad, pad + width, pad + height))
    bounds = padded.getbbox()
    assert bounds is None or (bounds[0] >= pad and bounds[1] >= pad and
                             bounds[2] <= pad + width and bounds[3] <= pad + height), (chr(cp), bounds)
    return image


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("font", type=Path)
    args = parser.parse_args()
    expected = "68a3fc98800b2a27b371f2fb79991daf3633bd89309d4ffaa6946fd587f375b5"
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != expected:
        parser.error("Font input does not match the locked Noto CJK SHA256")
    rows = catalog()
    chars = sorted({ord(c) for row in rows for text in row for c in text if ord(c) >= 128}
                   | {ord(c) for c in "简体中文繁體中文日本語"} | set(range(32, 127)))
    cmap = TTFont(args.font).getBestCmap()
    assert all(cp in cmap for cp in chars), "Missing upstream glyph"
    header = "/* Generated by tools/generate_ui_resources.py; do not hand-edit. */\n"
    font_header = header + "/* Derived from Noto Sans CJK JP. Copyright 2014-2021 Adobe.\n * SPDX-License-Identifier: OFL-1.1; see licenses/Noto-CJK-OFL-1.1.txt. */\n"
    target = ROOT / "components/vibe_ui/generated"
    target.mkdir(parents=True, exist_ok=True)
    messages = header + '#include "vibe_i18n.h"\nconst vibe_message_t vibe_messages[] = {\n'
    messages += "\n".join("    {{" + ", ".join(json.dumps(t, ensure_ascii=False) for t in row) + "}}," for row in rows)
    messages += "\n};\nconst size_t vibe_message_count = sizeof(vibe_messages)/sizeof(vibe_messages[0]);\n"
    (target / "vibe_messages.c").write_text(messages)
    # Same 16px em for Latin/CJK, with space for real ascenders/descenders.
    note_font = ImageFont.truetype(str(args.font), 16)
    glyphs = font_header + '#include "vibe_i18n.h"\nconst uint32_t vibe_glyph_codepoints[] = {'
    glyphs += ",".join(str(cp) for cp in chars) + "};\n"
    glyphs += "const size_t vibe_glyph_count = sizeof(vibe_glyph_codepoints)/sizeof(vibe_glyph_codepoints[0]);\n"
    advances = []
    glyphs += "const uint32_t vibe_glyph_rows[][20] = {\n"
    for cp in chars:
        image = bitmap(note_font, cp, 20, 20, 15)
        bounds = image.getbbox()
        advances.append(max(math.ceil(note_font.getlength(chr(cp))), bounds[2] if bounds else 0))
        pixels = list(image.getdata())
        # 50% coverage, rather than the previous 38% stroke expansion.
        bits = [sum((1 << (19 - x)) for x in range(20) if pixels[y * 20 + x] >= 128) for y in range(20)]
        assert cp == 32 or any(bits), hex(cp)
        glyphs += "    {" + ",".join(hex(b) for b in bits) + "},\n"
    glyphs += "};\n"
    glyphs += "const uint8_t vibe_glyph_advances[] = {" + ",".join(map(str, advances)) + "};\n"
    (target / "vibe_glyphs.c").write_text(glyphs)
    # Logical sizes preserve existing layout heights; actual em is selected by
    # the face's shared ascent/descent, not by resizing individual characters.
    for size, em, line_height, baseline in [(12, 12, 16, 12), (14, 13, 16, 12), (20, 18, 22, 17)]:
        font = ImageFont.truetype(str(args.font), em)
        data = []
        descriptors = ["    {0},"]
        for cp in chars:
            raster = bitmap(font, cp, size + 2, line_height, baseline)
            pixels = list(raster.getdata())
            bounds = raster.getbbox()
            advance = max(math.ceil(font.getlength(chr(cp))), bounds[2] if bounds else 0)
            descriptors.append(f"    {{.bitmap_index={len(data)}, .adv_w={advance * 16}, .box_w={size + 2}, .box_h={line_height}, .ofs_x=0, .ofs_y={baseline - line_height}}},")
            if len(pixels) % 2: pixels.append(0)
            data.extend((pixels[i] // 17) * 16 + pixels[i + 1] // 17 for i in range(0, len(pixels), 2))
        out = font_header + '#include "lvgl.h"\n'
        out += "static const uint8_t bitmap[] = {\n" + "\n".join(
            "    " + ",".join(str(b) for b in data[i:i+24]) + "," for i in range(0, len(data), 24)) + "\n};\n"
        out += "static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {\n" + "\n".join(descriptors) + "\n};\n"
        out += "static const uint16_t unicode[] = {" + ",".join(str(cp - 32) for cp in chars) + "};\n"
        out += f"static const lv_font_fmt_txt_cmap_t cmaps[] = {{{{.range_start=32, .range_length={chars[-1] - 31}, .glyph_id_start=1, .unicode_list=unicode, .list_length={len(chars)}, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}}};\n"
        out += "static const lv_font_fmt_txt_dsc_t dsc = {.glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=4};\n"
        out += f"const lv_font_t vibe_font_{size} = {{.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height={line_height}, .base_line={line_height - baseline}, .dsc=&dsc}};\n"
        (target / f"vibe_font_{size}.c").write_text(out)
    print(f"Generated {len(rows)} messages / {len(chars)} Latin/CJK glyphs; upstream SHA256 {hashlib.sha256(args.font.read_bytes()).hexdigest()}")


if __name__ == "__main__":
    main()
