#!/usr/bin/env python3
"""Generate bounded dynamic task fonts from the same locked Noto UI source.

Coverage is the union of GB2312, Big5 and Shift-JIS printable CJK characters,
plus printable ASCII. Separate task fonts avoid multiplying dynamic content
coverage across every UI size. Normal firmware builds consume checked-in C.
"""
import argparse
import hashlib
from pathlib import Path
from PIL import ImageFont
from fontTools.ttLib import TTFont
from generate_ui_resources import bitmap

ROOT = Path(__file__).resolve().parents[1]
SHA256 = '68a3fc98800b2a27b371f2fb79991daf3633bd89309d4ffaa6946fd587f375b5'


def task_codepoints(cmap):
    chars = set(range(32, 127))
    for cp in range(0x3000, 0xFFEF + 1):
        if cp not in cmap:
            continue
        for codec in ('gb2312', 'big5', 'shift_jis'):
            try:
                chr(cp).encode(codec)
                chars.add(cp)
                break
            except UnicodeEncodeError:
                pass
    return sorted(chars)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('font', type=Path)
    args = parser.parse_args()
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != SHA256:
        parser.error('Font input does not match the locked Noto CJK SHA256')
    candidates = task_codepoints(TTFont(args.font).getBestCmap())
    passport_face = ImageFont.truetype(str(args.font), 12)
    note_face = ImageFont.truetype(str(args.font), 16)
    chars, omitted = [], []
    for cp in candidates:
        try:
            bitmap(passport_face, cp, 14, 16, 12)
            bitmap(note_face, cp, 20, 20, 15)
            chars.append(cp)
        except AssertionError:
            # Explicitly omit out-of-baseline marks, never crop or recenter ink.
            omitted.append(cp)
    print('Out-of-baseline marks omitted: ' + ', '.join(f'U+{cp:04X}' for cp in omitted))
    header = ('/* Generated by tools/generate_todo_fonts.py; do not hand-edit. */\n'
              '/* Derived from Noto Sans CJK JP. Copyright 2014-2021 Adobe.\n'
              ' * SPDX-License-Identifier: OFL-1.1; see licenses/Noto-CJK-OFL-1.1.txt. */\n')
    out = ROOT / 'components/vibe_ui/generated'
    font = ImageFont.truetype(str(args.font), 12)
    descriptors = ['    {0},']
    data = []
    for cp in chars:
        raster = bitmap(font, cp, 14, 16, 12)
        pixels = list(raster.getdata())
        advance = max(round(font.getlength(chr(cp))), raster.getbbox()[2] if raster.getbbox() else 0)
        descriptors.append(f'    {{.bitmap_index={len(data)}, .adv_w={advance*16}, .box_w=14, .box_h=16, .ofs_x=0, .ofs_y=-4}},')
        data.extend(sum((1 << (7-j)) for j in range(8) if pixels[i+j] >= 128)
                    for i in range(0, len(pixels), 8))
    text = header + '#include "lvgl.h"\nstatic const uint8_t bitmap[] = {\n'
    text += '\n'.join('    '+','.join(str(b) for b in data[i:i+28])+',' for i in range(0,len(data),28))+'\n};\n'
    text += 'static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {\n'+'\n'.join(descriptors)+'\n};\n'
    text += 'static const uint16_t unicode[] = {'+','.join(str(cp-32) for cp in chars)+'};\n'
    text += f'static const lv_font_fmt_txt_cmap_t cmaps[] = {{{{.range_start=32, .range_length={chars[-1]-31}, .glyph_id_start=1, .unicode_list=unicode, .list_length={len(chars)}, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}}};\n'
    text += 'static const lv_font_fmt_txt_dsc_t dsc = {.glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=1};\n'
    text += 'const lv_font_t vibe_todo_font_12 = {.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height=16, .base_line=4, .dsc=&dsc};\n'
    (out / 'vibe_todo_font_12.c').write_text(text)
    font = ImageFont.truetype(str(args.font), 16)
    rows, advances = [], []
    for cp in chars:
        raster = bitmap(font, cp, 20, 20, 15)
        pixels = list(raster.getdata())
        advances.append(max(round(font.getlength(chr(cp))), raster.getbbox()[2] if raster.getbbox() else 0))
        rows.append('    {'+','.join(hex(sum(1 << (19-x) for x in range(20) if pixels[y*20+x] >= 128)) for y in range(20))+'},')
    text = header + '#include "vibe_todo_font.h"\n'
    text += 'const uint32_t vibe_todo_codepoints[] = {'+','.join(map(str, chars))+'};\n'
    text += f'const size_t vibe_todo_glyph_count = {len(chars)};\n'
    text += 'const uint32_t vibe_todo_glyph_rows[][20] = {\n'+'\n'.join(rows)+'\n};\n'
    text += 'const uint8_t vibe_todo_glyph_advances[] = {'+','.join(map(str, advances))+'};\n'
    (out / 'vibe_todo_glyphs.c').write_text(text)
    print(f'Generated dynamic TODO fonts: {len(chars)} glyphs; Passport packed bitmap {len(data)} bytes')


if __name__ == '__main__':
    main()
